/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProPatientsRouteImport } from './routes/pro.patients'
import { Route as ProDashboardRouteImport } from './routes/pro.dashboard'
import { Route as PatientHomeRouteImport } from './routes/patient.home'
import { Route as ProPatientsPatientIdRouteImport } from './routes/pro.patients.$patientId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProPatientsRoute = ProPatientsRouteImport.update({
  id: '/pro/patients',
  path: '/pro/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const ProDashboardRoute = ProDashboardRouteImport.update({
  id: '/pro/dashboard',
  path: '/pro/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientHomeRoute = PatientHomeRouteImport.update({
  id: '/patient/home',
  path: '/patient/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ProPatientsPatientIdRoute = ProPatientsPatientIdRouteImport.update({
  id: '/$patientId',
  path: '/$patientId',
  getParentRoute: () => ProPatientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/patient/home': typeof PatientHomeRoute
  '/pro/dashboard': typeof ProDashboardRoute
  '/pro/patients': typeof ProPatientsRouteWithChildren
  '/pro/patients/$patientId': typeof ProPatientsPatientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/patient/home': typeof PatientHomeRoute
  '/pro/dashboard': typeof ProDashboardRoute
  '/pro/patients': typeof ProPatientsRouteWithChildren
  '/pro/patients/$patientId': typeof ProPatientsPatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/patient/home': typeof PatientHomeRoute
  '/pro/dashboard': typeof ProDashboardRoute
  '/pro/patients': typeof ProPatientsRouteWithChildren
  '/pro/patients/$patientId': typeof ProPatientsPatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/login'
    | '/register'
    | '/patient/home'
    | '/pro/dashboard'
    | '/pro/patients'
    | '/pro/patients/$patientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/login'
    | '/register'
    | '/patient/home'
    | '/pro/dashboard'
    | '/pro/patients'
    | '/pro/patients/$patientId'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/login'
    | '/register'
    | '/patient/home'
    | '/pro/dashboard'
    | '/pro/patients'
    | '/pro/patients/$patientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  PatientHomeRoute: typeof PatientHomeRoute
  ProDashboardRoute: typeof ProDashboardRoute
  ProPatientsRoute: typeof ProPatientsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/patients': {
      id: '/pro/patients'
      path: '/pro/patients'
      fullPath: '/pro/patients'
      preLoaderRoute: typeof ProPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/dashboard': {
      id: '/pro/dashboard'
      path: '/pro/dashboard'
      fullPath: '/pro/dashboard'
      preLoaderRoute: typeof ProDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/home': {
      id: '/patient/home'
      path: '/patient/home'
      fullPath: '/patient/home'
      preLoaderRoute: typeof PatientHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/patients/$patientId': {
      id: '/pro/patients/$patientId'
      path: '/$patientId'
      fullPath: '/pro/patients/$patientId'
      preLoaderRoute: typeof ProPatientsPatientIdRouteImport
      parentRoute: typeof ProPatientsRoute
    }
  }
}

interface ProPatientsRouteChildren {
  ProPatientsPatientIdRoute: typeof ProPatientsPatientIdRoute
}

const ProPatientsRouteChildren: ProPatientsRouteChildren = {
  ProPatientsPatientIdRoute: ProPatientsPatientIdRoute,
}

const ProPatientsRouteWithChildren = ProPatientsRoute._addFileChildren(
  ProPatientsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  PatientHomeRoute: PatientHomeRoute,
  ProDashboardRoute: ProDashboardRoute,
  ProPatientsRoute: ProPatientsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
