/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProSportRouteImport } from './routes/pro.sport'
import { Route as ProRecipesRouteImport } from './routes/pro.recipes'
import { Route as ProPatientsRouteImport } from './routes/pro.patients'
import { Route as ProNutritionRouteImport } from './routes/pro.nutrition'
import { Route as ProDashboardRouteImport } from './routes/pro.dashboard'
import { Route as ProConsultationsRouteImport } from './routes/pro.consultations'
import { Route as PatientProfilRouteImport } from './routes/patient.profil'
import { Route as PatientHomeRouteImport } from './routes/patient.home'
import { Route as PatientDashboardRouteImport } from './routes/patient.dashboard'
import { Route as PatientConsultationsRouteImport } from './routes/patient.consultations'
import { Route as ProSportProgramIdRouteImport } from './routes/pro.sport.$programId'
import { Route as ProRecipesNewRouteImport } from './routes/pro.recipes.new'
import { Route as ProPatientsPatientIdRouteImport } from './routes/pro.patients.$patientId'
import { Route as ProNutritionProgramIdRouteImport } from './routes/pro.nutrition.$programId'
import { Route as ProConsultationsIdRouteImport } from './routes/pro.consultations.$id'
import { Route as PatientPayConsultationIdRouteImport } from './routes/patient.pay.$consultationId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProSportRoute = ProSportRouteImport.update({
  id: '/pro/sport',
  path: '/pro/sport',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRecipesRoute = ProRecipesRouteImport.update({
  id: '/pro/recipes',
  path: '/pro/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProPatientsRoute = ProPatientsRouteImport.update({
  id: '/pro/patients',
  path: '/pro/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const ProNutritionRoute = ProNutritionRouteImport.update({
  id: '/pro/nutrition',
  path: '/pro/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const ProDashboardRoute = ProDashboardRouteImport.update({
  id: '/pro/dashboard',
  path: '/pro/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProConsultationsRoute = ProConsultationsRouteImport.update({
  id: '/pro/consultations',
  path: '/pro/consultations',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientProfilRoute = PatientProfilRouteImport.update({
  id: '/patient/profil',
  path: '/patient/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientHomeRoute = PatientHomeRouteImport.update({
  id: '/patient/home',
  path: '/patient/home',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientDashboardRoute = PatientDashboardRouteImport.update({
  id: '/patient/dashboard',
  path: '/patient/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientConsultationsRoute = PatientConsultationsRouteImport.update({
  id: '/patient/consultations',
  path: '/patient/consultations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProSportProgramIdRoute = ProSportProgramIdRouteImport.update({
  id: '/$programId',
  path: '/$programId',
  getParentRoute: () => ProSportRoute,
} as any)
const ProRecipesNewRoute = ProRecipesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProRecipesRoute,
} as any)
const ProPatientsPatientIdRoute = ProPatientsPatientIdRouteImport.update({
  id: '/$patientId',
  path: '/$patientId',
  getParentRoute: () => ProPatientsRoute,
} as any)
const ProNutritionProgramIdRoute = ProNutritionProgramIdRouteImport.update({
  id: '/$programId',
  path: '/$programId',
  getParentRoute: () => ProNutritionRoute,
} as any)
const ProConsultationsIdRoute = ProConsultationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProConsultationsRoute,
} as any)
const PatientPayConsultationIdRoute =
  PatientPayConsultationIdRouteImport.update({
    id: '/patient/pay/$consultationId',
    path: '/patient/pay/$consultationId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/patient/consultations': typeof PatientConsultationsRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/home': typeof PatientHomeRoute
  '/patient/profil': typeof PatientProfilRoute
  '/pro/consultations': typeof ProConsultationsRouteWithChildren
  '/pro/dashboard': typeof ProDashboardRoute
  '/pro/nutrition': typeof ProNutritionRouteWithChildren
  '/pro/patients': typeof ProPatientsRouteWithChildren
  '/pro/recipes': typeof ProRecipesRouteWithChildren
  '/pro/sport': typeof ProSportRouteWithChildren
  '/patient/pay/$consultationId': typeof PatientPayConsultationIdRoute
  '/pro/consultations/$id': typeof ProConsultationsIdRoute
  '/pro/nutrition/$programId': typeof ProNutritionProgramIdRoute
  '/pro/patients/$patientId': typeof ProPatientsPatientIdRoute
  '/pro/recipes/new': typeof ProRecipesNewRoute
  '/pro/sport/$programId': typeof ProSportProgramIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/patient/consultations': typeof PatientConsultationsRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/home': typeof PatientHomeRoute
  '/patient/profil': typeof PatientProfilRoute
  '/pro/consultations': typeof ProConsultationsRouteWithChildren
  '/pro/dashboard': typeof ProDashboardRoute
  '/pro/nutrition': typeof ProNutritionRouteWithChildren
  '/pro/patients': typeof ProPatientsRouteWithChildren
  '/pro/recipes': typeof ProRecipesRouteWithChildren
  '/pro/sport': typeof ProSportRouteWithChildren
  '/patient/pay/$consultationId': typeof PatientPayConsultationIdRoute
  '/pro/consultations/$id': typeof ProConsultationsIdRoute
  '/pro/nutrition/$programId': typeof ProNutritionProgramIdRoute
  '/pro/patients/$patientId': typeof ProPatientsPatientIdRoute
  '/pro/recipes/new': typeof ProRecipesNewRoute
  '/pro/sport/$programId': typeof ProSportProgramIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/patient/consultations': typeof PatientConsultationsRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/home': typeof PatientHomeRoute
  '/patient/profil': typeof PatientProfilRoute
  '/pro/consultations': typeof ProConsultationsRouteWithChildren
  '/pro/dashboard': typeof ProDashboardRoute
  '/pro/nutrition': typeof ProNutritionRouteWithChildren
  '/pro/patients': typeof ProPatientsRouteWithChildren
  '/pro/recipes': typeof ProRecipesRouteWithChildren
  '/pro/sport': typeof ProSportRouteWithChildren
  '/patient/pay/$consultationId': typeof PatientPayConsultationIdRoute
  '/pro/consultations/$id': typeof ProConsultationsIdRoute
  '/pro/nutrition/$programId': typeof ProNutritionProgramIdRoute
  '/pro/patients/$patientId': typeof ProPatientsPatientIdRoute
  '/pro/recipes/new': typeof ProRecipesNewRoute
  '/pro/sport/$programId': typeof ProSportProgramIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/login'
    | '/register'
    | '/patient/consultations'
    | '/patient/dashboard'
    | '/patient/home'
    | '/patient/profil'
    | '/pro/consultations'
    | '/pro/dashboard'
    | '/pro/nutrition'
    | '/pro/patients'
    | '/pro/recipes'
    | '/pro/sport'
    | '/patient/pay/$consultationId'
    | '/pro/consultations/$id'
    | '/pro/nutrition/$programId'
    | '/pro/patients/$patientId'
    | '/pro/recipes/new'
    | '/pro/sport/$programId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/login'
    | '/register'
    | '/patient/consultations'
    | '/patient/dashboard'
    | '/patient/home'
    | '/patient/profil'
    | '/pro/consultations'
    | '/pro/dashboard'
    | '/pro/nutrition'
    | '/pro/patients'
    | '/pro/recipes'
    | '/pro/sport'
    | '/patient/pay/$consultationId'
    | '/pro/consultations/$id'
    | '/pro/nutrition/$programId'
    | '/pro/patients/$patientId'
    | '/pro/recipes/new'
    | '/pro/sport/$programId'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/login'
    | '/register'
    | '/patient/consultations'
    | '/patient/dashboard'
    | '/patient/home'
    | '/patient/profil'
    | '/pro/consultations'
    | '/pro/dashboard'
    | '/pro/nutrition'
    | '/pro/patients'
    | '/pro/recipes'
    | '/pro/sport'
    | '/patient/pay/$consultationId'
    | '/pro/consultations/$id'
    | '/pro/nutrition/$programId'
    | '/pro/patients/$patientId'
    | '/pro/recipes/new'
    | '/pro/sport/$programId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  PatientConsultationsRoute: typeof PatientConsultationsRoute
  PatientDashboardRoute: typeof PatientDashboardRoute
  PatientHomeRoute: typeof PatientHomeRoute
  PatientProfilRoute: typeof PatientProfilRoute
  ProConsultationsRoute: typeof ProConsultationsRouteWithChildren
  ProDashboardRoute: typeof ProDashboardRoute
  ProNutritionRoute: typeof ProNutritionRouteWithChildren
  ProPatientsRoute: typeof ProPatientsRouteWithChildren
  ProRecipesRoute: typeof ProRecipesRouteWithChildren
  ProSportRoute: typeof ProSportRouteWithChildren
  PatientPayConsultationIdRoute: typeof PatientPayConsultationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/sport': {
      id: '/pro/sport'
      path: '/pro/sport'
      fullPath: '/pro/sport'
      preLoaderRoute: typeof ProSportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/recipes': {
      id: '/pro/recipes'
      path: '/pro/recipes'
      fullPath: '/pro/recipes'
      preLoaderRoute: typeof ProRecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/patients': {
      id: '/pro/patients'
      path: '/pro/patients'
      fullPath: '/pro/patients'
      preLoaderRoute: typeof ProPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/nutrition': {
      id: '/pro/nutrition'
      path: '/pro/nutrition'
      fullPath: '/pro/nutrition'
      preLoaderRoute: typeof ProNutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/dashboard': {
      id: '/pro/dashboard'
      path: '/pro/dashboard'
      fullPath: '/pro/dashboard'
      preLoaderRoute: typeof ProDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/consultations': {
      id: '/pro/consultations'
      path: '/pro/consultations'
      fullPath: '/pro/consultations'
      preLoaderRoute: typeof ProConsultationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/profil': {
      id: '/patient/profil'
      path: '/patient/profil'
      fullPath: '/patient/profil'
      preLoaderRoute: typeof PatientProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/home': {
      id: '/patient/home'
      path: '/patient/home'
      fullPath: '/patient/home'
      preLoaderRoute: typeof PatientHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/dashboard': {
      id: '/patient/dashboard'
      path: '/patient/dashboard'
      fullPath: '/patient/dashboard'
      preLoaderRoute: typeof PatientDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/consultations': {
      id: '/patient/consultations'
      path: '/patient/consultations'
      fullPath: '/patient/consultations'
      preLoaderRoute: typeof PatientConsultationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/sport/$programId': {
      id: '/pro/sport/$programId'
      path: '/$programId'
      fullPath: '/pro/sport/$programId'
      preLoaderRoute: typeof ProSportProgramIdRouteImport
      parentRoute: typeof ProSportRoute
    }
    '/pro/recipes/new': {
      id: '/pro/recipes/new'
      path: '/new'
      fullPath: '/pro/recipes/new'
      preLoaderRoute: typeof ProRecipesNewRouteImport
      parentRoute: typeof ProRecipesRoute
    }
    '/pro/patients/$patientId': {
      id: '/pro/patients/$patientId'
      path: '/$patientId'
      fullPath: '/pro/patients/$patientId'
      preLoaderRoute: typeof ProPatientsPatientIdRouteImport
      parentRoute: typeof ProPatientsRoute
    }
    '/pro/nutrition/$programId': {
      id: '/pro/nutrition/$programId'
      path: '/$programId'
      fullPath: '/pro/nutrition/$programId'
      preLoaderRoute: typeof ProNutritionProgramIdRouteImport
      parentRoute: typeof ProNutritionRoute
    }
    '/pro/consultations/$id': {
      id: '/pro/consultations/$id'
      path: '/$id'
      fullPath: '/pro/consultations/$id'
      preLoaderRoute: typeof ProConsultationsIdRouteImport
      parentRoute: typeof ProConsultationsRoute
    }
    '/patient/pay/$consultationId': {
      id: '/patient/pay/$consultationId'
      path: '/patient/pay/$consultationId'
      fullPath: '/patient/pay/$consultationId'
      preLoaderRoute: typeof PatientPayConsultationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProConsultationsRouteChildren {
  ProConsultationsIdRoute: typeof ProConsultationsIdRoute
}

const ProConsultationsRouteChildren: ProConsultationsRouteChildren = {
  ProConsultationsIdRoute: ProConsultationsIdRoute,
}

const ProConsultationsRouteWithChildren =
  ProConsultationsRoute._addFileChildren(ProConsultationsRouteChildren)

interface ProNutritionRouteChildren {
  ProNutritionProgramIdRoute: typeof ProNutritionProgramIdRoute
}

const ProNutritionRouteChildren: ProNutritionRouteChildren = {
  ProNutritionProgramIdRoute: ProNutritionProgramIdRoute,
}

const ProNutritionRouteWithChildren = ProNutritionRoute._addFileChildren(
  ProNutritionRouteChildren,
)

interface ProPatientsRouteChildren {
  ProPatientsPatientIdRoute: typeof ProPatientsPatientIdRoute
}

const ProPatientsRouteChildren: ProPatientsRouteChildren = {
  ProPatientsPatientIdRoute: ProPatientsPatientIdRoute,
}

const ProPatientsRouteWithChildren = ProPatientsRoute._addFileChildren(
  ProPatientsRouteChildren,
)

interface ProRecipesRouteChildren {
  ProRecipesNewRoute: typeof ProRecipesNewRoute
}

const ProRecipesRouteChildren: ProRecipesRouteChildren = {
  ProRecipesNewRoute: ProRecipesNewRoute,
}

const ProRecipesRouteWithChildren = ProRecipesRoute._addFileChildren(
  ProRecipesRouteChildren,
)

interface ProSportRouteChildren {
  ProSportProgramIdRoute: typeof ProSportProgramIdRoute
}

const ProSportRouteChildren: ProSportRouteChildren = {
  ProSportProgramIdRoute: ProSportProgramIdRoute,
}

const ProSportRouteWithChildren = ProSportRoute._addFileChildren(
  ProSportRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  PatientConsultationsRoute: PatientConsultationsRoute,
  PatientDashboardRoute: PatientDashboardRoute,
  PatientHomeRoute: PatientHomeRoute,
  PatientProfilRoute: PatientProfilRoute,
  ProConsultationsRoute: ProConsultationsRouteWithChildren,
  ProDashboardRoute: ProDashboardRoute,
  ProNutritionRoute: ProNutritionRouteWithChildren,
  ProPatientsRoute: ProPatientsRouteWithChildren,
  ProRecipesRoute: ProRecipesRouteWithChildren,
  ProSportRoute: ProSportRouteWithChildren,
  PatientPayConsultationIdRoute: PatientPayConsultationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
